### PR TITLE
Testing on JS

### PR DESCRIPTION
**Pull request by exoego**

### CODE REVIEW

**Comment by er1c** [comment]
@exoego I'm excited about this

**Comment by exoego** [comment]
It seems that test codes/production codes uses some class/methods which does not have Scala.js implementation...


* `class java.io.CharArrayWriter` 
* `class java.lang.reflect.Field`  
* `class java.lang.reflect.Type`
* `class java.lang.reflect.Method`
* `method org.apache.commons.lang3.BooleanUtilsTest.assertThrows(scala.Function0,scala.reflect.ClassTag,org.scalactic.source.Position)org.scalatest.compatible.Assertion`

**Comment by er1c** [comment]
We can look into the usage of `CharArrayWriter` and determine if it should be implemented in scala.js or just rewrite the code that uses it.  The methods that use `reflect` should be moved to a `jvm` specific trait or converted to scala.reflect if scala.js supports them.

**Comment by er1c** [comment]
Not sure about assertThrows either and how that works with Scala.js

**Comment by er1c** [comment]
@exoego are you able to prune out the ones that succeed vs the ones that fail - we can get the ones that succeed merged at least

**Comment by exoego** [comment]
Sorry, I cannot work on this PR for several days due to replacing my laptop PC.
It is fine to take over.
I will work again after replacing my PC.

**Comment by er1c** [comment]
Replaced by https://github.com/er1c/scala-apache-commons-lang3/pull/33 - flushed out a lot more incompatabilities :/

**Pull request closed without merging**
